baseurl = "/"
title = "Programmer in Progress"
theme = "hyde-custom"

[Params]
    mainSections = ["post"]
    intro = true
    headline = ""
    description = "My CS journey"
    github = "https://github.com/joaogui1"
    twitter = "https://twitter.com/iugoaoj"
    email = "joaoguilhermearujo@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "2 Jan, 2006"

[Menus]
  main = [
      {Name = "About", URL = "/page/about"},
      {Name = "Resources", URL = "/page/resources"},
      {Name = "Blog", URL = "/post/"},
      {Name = "Github", URL = "https://github.com/joaogui1"}
  ]